Update providers.bzl
On Bazel 5.0, I am getting below error:
```sh
File "/home/ajithu/.cache/bazel/_bazel_ajithu/3e767109738c8b2d608cdfe5de369b17/external/io_bazel_rules_docker/container/providers.bzl", line 52, column 20, in PushInfo
		PushInfo = provider(fields = [
Error: unexpected keywords stamp, stamp, stamp, stamp_inputs, tag in call to instantiate provider PushInfo
```sh

It looks like we need to delete `stamp_inputs` and `tags` as well