Fix broken tests resulting from pip dropping support for legacy Python versions. The tests are using a base image that only has python3.5 and currently the run_arbitrary tests are failing with
```
stderr: Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

This was fixed upstream in https://github.com/pyenv/pyenv/pull/1793 but it is not clear to me how/when we can expect to see that as part of launcher.gcr.io/google/bazel:latest.